"""
/api/create-appointment.py
===========================
Vercel Serverless Function — creates a Google Calendar event
with a real Google Meet link using a Service Account.

POST /api/create-appointment
Body:
  {
    doctor_name:    string,
    doctor_email:   string,
    patient_name:   string,
    patient_email:  string,
    slot_datetime:  string   (ISO 8601, e.g. "2026-04-16T10:00:00")
  }

Returns:
  { meet_link, event_id, event_link }

Environment variables needed (set in Vercel dashboard):
  GOOGLE_SERVICE_ACCOUNT_JSON   — full JSON string of service account key
  GOOGLE_CALENDAR_ID            — "primary" or specific calendar ID
"""

import json
import os
from datetime import datetime, timedelta
from http.server import BaseHTTPRequestHandler


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _json_response(handler_self, status: int, data: dict) -> None:
    """Write a JSON HTTP response."""
    body = json.dumps(data).encode("utf-8")
    handler_self.send_response(status)
    handler_self.send_header("Content-Type", "application/json")
    handler_self.send_header("Content-Length", str(len(body)))
    handler_self.send_header("Access-Control-Allow-Origin", "*")
    handler_self.end_headers()
    handler_self.wfile.write(body)


def _create_meet_event(
    service_account_json: str,
    calendar_id: str,
    doctor_name: str,
    doctor_email: str,
    patient_name: str,
    patient_email: str,
    slot_dt: datetime,
    duration_minutes: int = 30,
) -> dict:
    """
    Creates a Google Calendar event with a Google Meet room.
    Uses Service Account credentials (no browser login required).

    The service account must:
      1. Have domain-wide delegation enabled (for G Suite / Workspace), OR
      2. Be granted "Make changes to events" permission on the doctor's calendar.
    """
    from google.oauth2 import service_account
    from googleapiclient.discovery import build

    # Parse service account JSON from env var string
    sa_info = json.loads(service_account_json)

    credentials = service_account.Credentials.from_service_account_info(
        sa_info,
        scopes=["https://www.googleapis.com/auth/calendar"],
    )

    # Optional: impersonate the doctor's email (requires domain-wide delegation)
    # credentials = credentials.with_subject(doctor_email)

    service = build("calendar", "v3", credentials=credentials)

    end_dt = slot_dt + timedelta(minutes=duration_minutes)

    attendees = []
    if doctor_email:
        attendees.append({"email": doctor_email,  "displayName": doctor_name})
    if patient_email:
        attendees.append({"email": patient_email, "displayName": patient_name})

    event_body = {
        "summary":     f"DERMA AI Consultation — {patient_name} with {doctor_name}",
        "description": (
            f"DERMA AI Telemedicine Consultation\n"
            f"Doctor:  {doctor_name}\n"
            f"Patient: {patient_name}\n\n"
            f"Join via Google Meet at the scheduled time."
        ),
        "start": {"dateTime": slot_dt.isoformat(), "timeZone": "Asia/Kolkata"},
        "end":   {"dateTime": end_dt.isoformat(),   "timeZone": "Asia/Kolkata"},
        "attendees": attendees,
        "conferenceData": {
            "createRequest": {
                "requestId":             f"derma-ai-{int(slot_dt.timestamp())}",
                "conferenceSolutionKey": {"type": "hangoutsMeet"},
            }
        },
        "reminders": {
            "useDefault": False,
            "overrides": [
                {"method": "email",  "minutes": 60},
                {"method": "popup",  "minutes": 10},
            ],
        },
        "sendUpdates": "all",
    }

    event = service.events().insert(
        calendarId=calendar_id,
        body=event_body,
        conferenceDataVersion=1,   # REQUIRED for Meet link
        sendNotifications=True,
    ).execute()

    # Extract the Google Meet URL
    entry_points = event.get("conferenceData", {}).get("entryPoints", [])
    meet_link = next(
        (ep["uri"] for ep in entry_points if ep.get("entryPointType") == "video"),
        None,
    )

    if not meet_link:
        raise ValueError("Google Meet link was not generated by the Calendar API.")

    return {
        "meet_link":   meet_link,
        "event_id":    event["id"],
        "event_link":  event.get("htmlLink", ""),
    }


# ─── Vercel Handler ───────────────────────────────────────────────────────────

class handler(BaseHTTPRequestHandler):

    def do_OPTIONS(self):
        """CORS preflight."""
        self.send_response(204)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type, Authorization")
        self.end_headers()

    def do_POST(self):
        # ── Read body ─────────────────────────────────────────────────────────
        try:
            length = int(self.headers.get("Content-Length", 0))
            body   = self.rfile.read(length)
            data   = json.loads(body)
        except Exception:
            return _json_response(self, 400, {"error": "Invalid JSON body"})

        # ── Validate required fields ──────────────────────────────────────────
        required = ["doctor_name", "patient_name", "slot_datetime"]
        missing  = [f for f in required if not data.get(f)]
        if missing:
            return _json_response(self, 400, {"error": f"Missing: {', '.join(missing)}"})

        # ── Parse datetime ────────────────────────────────────────────────────
        try:
            slot_dt = datetime.fromisoformat(data["slot_datetime"])
        except ValueError:
            return _json_response(self, 400, {"error": "Invalid slot_datetime — use ISO 8601"})

        # ── Read environment vars ─────────────────────────────────────────────
        sa_json     = os.environ.get("GOOGLE_SERVICE_ACCOUNT_JSON", "")
        calendar_id = os.environ.get("GOOGLE_CALENDAR_ID", "primary")

        if not sa_json:
            return _json_response(self, 500, {
                "error": "GOOGLE_SERVICE_ACCOUNT_JSON not configured in environment"
            })

        # ── Create calendar event ─────────────────────────────────────────────
        try:
            result = _create_meet_event(
                service_account_json = sa_json,
                calendar_id          = calendar_id,
                doctor_name          = data["doctor_name"],
                doctor_email         = data.get("doctor_email", ""),
                patient_name         = data["patient_name"],
                patient_email        = data.get("patient_email", ""),
                slot_dt              = slot_dt,
            )
            return _json_response(self, 200, result)

        except Exception as e:
            return _json_response(self, 500, {"error": f"Google Calendar API error: {str(e)}"})

    def log_message(self, *args):
        pass  # suppress default HTTP server logs in Vercel
